[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = ".next/serverless"

[[edge_functions]]
  function = "middleware"
  path = "/*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 