[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = ".next/serverless"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 